### PR TITLE
phpunit does not seem to be working correctly anymore in php 7+

### PR DESCRIPTION
**Pull request by NeoVance**
This commit provides updated thruway/client as well as phpunit

### CODE REVIEW

**Comment by Mulkave** [comment]
Thanks for the PR! This requires and update in travis.yml file as well in order to run the tests under php 7+ instead of 5+

**Comment by Mulkave** [comment]
Once this is done, will release a new version having all three changes together. Cheers!

**Comment by NeoVance** [comment]
Trying to figure out a way to split the tests, so that we can continue to test against at least 5.6 and 7.0+

Unfortunately every version of PHPUnit that supports 7.0+ *requires* 7.0+ dropping support for 5.x versions of PHP. Anyone have any thoughts on how to get around this? Most of my work with PHPUnit so far has targeted a single version of PHP, but I can see with Minion you might want to have some backwards compatibility.

**Comment by NeoVance** [comment]
This is going to break testing on PHP versions pre 7.0.

It might be possible to support it by aliasing the class name, and having users install their own global phpunit rather than requiring a specific version.

**Pull request merged**
